INSERT INTO imdbmicroservice.occupation (occupation) VALUES ('other');
INSERT INTO imdbmicroservice.occupation (occupation) VALUES ('academic');
INSERT INTO imdbmicroservice.occupation (occupation) VALUES ('artist');
INSERT INTO imdbmicroservice.occupation (occupation) VALUES ('clerical');
INSERT INTO imdbmicroservice.occupation (occupation) VALUES ('grad student');
INSERT INTO imdbmicroservice.occupation (occupation) VALUES ('customer service');
INSERT INTO imdbmicroservice.occupation (occupation) VALUES ('doctor care');
INSERT INTO imdbmicroservice.occupation (occupation) VALUES ('managerial');
INSERT INTO imdbmicroservice.occupation (occupation) VALUES ('farmer');
INSERT INTO imdbmicroservice.occupation (occupation) VALUES ('homemaker');
INSERT INTO imdbmicroservice.occupation (occupation) VALUES ('K-12 student');
INSERT INTO imdbmicroservice.occupation (occupation) VALUES ('lawyer');
INSERT INTO imdbmicroservice.occupation (occupation) VALUES ('programmer');
INSERT INTO imdbmicroservice.occupation (occupation) VALUES ('retired');
INSERT INTO imdbmicroservice.occupation (occupation) VALUES ('sales');
INSERT INTO imdbmicroservice.occupation (occupation) VALUES ('scientist');
INSERT INTO imdbmicroservice.occupation (occupation) VALUES ('self-employed');
INSERT INTO imdbmicroservice.occupation (occupation) VALUES ('engineer');
INSERT INTO imdbmicroservice.occupation (occupation) VALUES ('tradesman');
INSERT INTO imdbmicroservice.occupation (occupation) VALUES ('unemployed');
INSERT INTO imdbmicroservice.occupation (occupation) VALUES ('writer');