spring:
  application:
      name: user-service
  datasource:
      url: jdbc:mysql://localhost:3306/imdbmicroservice
      username: root
      password: 1
      dbcp:
        driver-class-name: com.mysql.jdbc.Driver
  data:
      rest:
        base-path: /api
# HTTP Server
server:
  port: 3333   # HTTP (Tomcat)

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5   # DO NOT DO THIS IN PRODUCTION